# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sistema Aplication Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'youtube-ios-player-helper'
  # Pods for Sistema Aplication Test

end
